# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Adunarea-si-scaderea-numerelor-in-virgula-mobila-main/SSC_P/SSC_P/SSC_P.cache/wt [current_project]
set_property parent.project_path D:/Adunarea-si-scaderea-numerelor-in-virgula-mobila-main/SSC_P/SSC_P/SSC_P.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Adunarea-si-scaderea-numerelor-in-virgula-mobila-main/SSC_P/SSC_P/SSC_P.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  D:/Adunarea-si-scaderea-numerelor-in-virgula-mobila-main/SSC_P/SSC_P/SSC_P.srcs/sources_1/new/SE.vhd
  D:/Adunarea-si-scaderea-numerelor-in-virgula-mobila-main/SSC_P/SSC_P/SSC_P.srcs/sources_1/new/CountLeadingZero.vhd
  D:/Adunarea-si-scaderea-numerelor-in-virgula-mobila-main/SSC_P/SSC_P/SSC_P.srcs/sources_1/new/ShiftLeft.vhd
  D:/Adunarea-si-scaderea-numerelor-in-virgula-mobila-main/SSC_P/SSC_P/SSC_P.srcs/sources_1/new/SignOut.vhd
  D:/Adunarea-si-scaderea-numerelor-in-virgula-mobila-main/SSC_P/SSC_P/SSC_P.srcs/sources_1/new/FractionAdd.vhd
  D:/Adunarea-si-scaderea-numerelor-in-virgula-mobila-main/SSC_P/SSC_P/SSC_P.srcs/sources_1/new/ShiftRight.vhd
  D:/Adunarea-si-scaderea-numerelor-in-virgula-mobila-main/SSC_P/SSC_P/SSC_P.srcs/sources_1/new/DepExpBlock.vhd
  D:/Adunarea-si-scaderea-numerelor-in-virgula-mobila-main/SSC_P/SSC_P/SSC_P.srcs/sources_1/new/CompExp.vhd
  D:/Adunarea-si-scaderea-numerelor-in-virgula-mobila-main/SSC_P/SSC_P/SSC_P.srcs/sources_1/new/Adder.vhd
  D:/Adunarea-si-scaderea-numerelor-in-virgula-mobila-main/SSC_P/SSC_P/SSC_P.srcs/sources_1/new/UC.vhd
  D:/Adunarea-si-scaderea-numerelor-in-virgula-mobila-main/SSC_P/SSC_P/SSC_P.srcs/sources_1/new/Normalizare.vhd
  D:/Adunarea-si-scaderea-numerelor-in-virgula-mobila-main/SSC_P/SSC_P/SSC_P.srcs/sources_1/new/SSD.vhd
  D:/Adunarea-si-scaderea-numerelor-in-virgula-mobila-main/SSC_P/SSC_P/SSC_P.srcs/sources_1/new/Decooder.vhd
  D:/Adunarea-si-scaderea-numerelor-in-virgula-mobila-main/SSC_P/SSC_P/SSC_P.srcs/sources_1/new/Debounce.vhd
  D:/Adunarea-si-scaderea-numerelor-in-virgula-mobila-main/SSC_P/SSC_P/SSC_P.srcs/sources_1/new/main.vhd
  D:/Adunarea-si-scaderea-numerelor-in-virgula-mobila-main/SSC_P/SSC_P/SSC_P.srcs/sources_1/new/PmodKYPD.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Adunarea-si-scaderea-numerelor-in-virgula-mobila-main/SSC_P/SSC_P/SSC_P.srcs/constrs_1/new/adunare_scadere_constrangeri.xdc
set_property used_in_implementation false [get_files D:/Adunarea-si-scaderea-numerelor-in-virgula-mobila-main/SSC_P/SSC_P/SSC_P.srcs/constrs_1/new/adunare_scadere_constrangeri.xdc]


synth_design -top PmodKYPD -part xc7a100tcsg324-1


write_checkpoint -force -noxdef PmodKYPD.dcp

catch { report_utilization -file PmodKYPD_utilization_synth.rpt -pb PmodKYPD_utilization_synth.pb }
